/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GmSSL */

#ifndef _Included_GmSSL
#define _Included_GmSSL
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     GmSSL
 * Method:    digest
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_froad_ukey_jni_GmSSL_digest
  (JNIEnv *, jobject, jstring, jbyteArray);


JNIEXPORT jlong JNICALL
Java_com_froad_ukey_jni_GmSSL_genRSAHash(JNIEnv *env, jobject instance,jint iAlgType, jboolean jisInit, jstring LeField_,
                            jbyteArray bPublicKey_, jint usPubKeyLen);

JNIEXPORT jlong JNICALL
Java_com_froad_ukey_jni_GmSSL_genRSAP10(JNIEnv *env, jobject instance,
                           jbyteArray bSignBuffer_, jint usSignLen);

JNIEXPORT jlong JNICALL
Java_com_froad_ukey_jni_GmSSL_genSM2Hash(JNIEnv *env, jobject instance, jboolean jisInit, jstring LeField_,
                            jbyteArray bPublicKey_, jint usPubKeyLen);

JNIEXPORT jlong JNICALL
Java_com_froad_ukey_jni_GmSSL_genSM2P10(JNIEnv *env, jobject instance,
                           jbyteArray bSignBuffer_, jint usSignLen);

JNIEXPORT jlong JNICALL
Java_com_froad_ukey_jni_GmSSL_convertPkcs7ToPemHex(JNIEnv *env, jobject instance,
                                                   jbyteArray bCerBuffer_, jint usCerLen);
#ifdef __cplusplus
}
#endif
#endif
